"""Create PPDA Table

Revision ID: 0bb11c65b4b1
Revises: d582e83af57b
Create Date: 2025-03-30 15:15:27.506134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0bb11c65b4b1'
down_revision: Union[str, None] = 'd582e83af57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppda',
    sa.Column('id_institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_ppda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_institution'], ['institution.id_institution'], ),
    sa.PrimaryKeyConstraint('id_ppda'),
    sa.UniqueConstraint('id_ppda')
    )
    op.add_column('action', sa.Column('id_ppda', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'action', 'ppda', ['id_ppda'], ['id_ppda'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_column('action', 'id_ppda')
    op.drop_table('ppda')
    # ### end Alembic commands ###
