"""Create deadline table

Revision ID: 0c0335b26536
Revises: 4b5c9f56d247
Create Date: 2025-03-30 19:53:36.512338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c0335b26536'
down_revision: Union[str, None] = '4b5c9f56d247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline',
    sa.Column('deadline_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_action', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('id_deadline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_action'], ['action.id_action'], ),
    sa.PrimaryKeyConstraint('id_deadline'),
    sa.UniqueConstraint('id_deadline')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadline')
    # ### end Alembic commands ###
