"""add deadline date as datetime in  DeadlIne

Revision ID: 152c74c63cd9
Revises: 8d520174f374
Create Date: 2025-04-04 19:05:33.311002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '152c74c63cd9'
down_revision: Union[str, None] = '8d520174f374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline', sa.Column('deadline_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadline', 'deadline_date')
    # ### end Alembic commands ###
