"""Create priorirty_type and messages relationship

Revision ID: 1999db39facf
Revises: 1dcbb08407da
Create Date: 2025-03-30 19:51:46.685786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1999db39facf'
down_revision: Union[str, None] = '1dcbb08407da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('id_priority_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'priority_type', ['id_priority_type'], ['id_priority_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'id_priority_type')
    # ### end Alembic commands ###
