"""empty message

Revision ID: 1c150280b496
Revises: 9f704b28da91
Create Date: 2025-01-26 20:32:32.737741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c150280b496'
down_revision: Union[str, None] = '9f704b28da91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institution', 'institution_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institution', 'institution_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
