"""Create Priority_type

Revision ID: 1dcbb08407da
Revises: 7066b2f89995
Create Date: 2025-03-30 19:49:15.959718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dcbb08407da'
down_revision: Union[str, None] = '7066b2f89995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_type',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_priority_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_priority_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority_type')
    # ### end Alembic commands ###
