"""remove deadline date from DeadlIne

Revision ID: 3a4aacd2f392
Revises: dcc07e060c7a
Create Date: 2025-04-04 19:04:29.943849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a4aacd2f392'
down_revision: Union[str, None] = 'dcc07e060c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadline', 'deadline_date')
    op.create_unique_constraint(None, 'history', ['id_history'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='unique')
    op.add_column('deadline', sa.Column('deadline_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
