"""[refactor] change id_creator for id_user in Acion table

Revision ID: 4feff87d9fde
Revises: a2a754316349
Create Date: 2025-04-12 11:47:03.254060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4feff87d9fde'
down_revision: Union[str, None] = 'a2a754316349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
