"""Create Priority_type

Revision ID: 7066b2f89995
Revises: aa14078b49e7
Create Date: 2025-03-30 19:48:18.215823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7066b2f89995'
down_revision: Union[str, None] = 'aa14078b49e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'message', ['id_message'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    # ### end Alembic commands ###
