"""[feat] Adds more fields to PPDA model

Revision ID: 7da3ee564779
Revises: 301fec342616
Create Date: 2025-04-28 17:53:33.109651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7da3ee564779'
down_revision: Union[str, None] = '301fec342616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppda', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ppda', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ppda', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ppda', sa.Column('municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ppda', sa.Column('geographic_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ppda', sa.Column('start_date', sa.Integer(), nullable=True))
    op.add_column('ppda', sa.Column('end_date', sa.Integer(), nullable=True))
    op.add_column('ppda', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ppda', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('ppda', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppda', 'updated_at')
    op.drop_column('ppda', 'created_at')
    op.drop_column('ppda', 'status')
    op.drop_column('ppda', 'end_date')
    op.drop_column('ppda', 'start_date')
    op.drop_column('ppda', 'geographic_scope')
    op.drop_column('ppda', 'municipality')
    op.drop_column('ppda', 'region')
    op.drop_column('ppda', 'description')
    op.drop_column('ppda', 'name')
    # ### end Alembic commands ###
