"""[refactor] change id_creator for id_user in Acion table

Revision ID: 7f8728b5c191
Revises: 4feff87d9fde
Create Date: 2025-04-12 11:47:42.943082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f8728b5c191'
down_revision: Union[str, None] = '4feff87d9fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('id_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('action_id_creator_fkey', 'action', type_='foreignkey')
    op.create_foreign_key(None, 'action', 'user', ['id_user'], ['id_user'])
    op.drop_column('action', 'id_creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('id_creator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.create_foreign_key('action_id_creator_fkey', 'action', 'user', ['id_creator'], ['id_user'])
    op.drop_column('action', 'id_user')
    # ### end Alembic commands ###
