"""add deadline date as datetime in  DeadlIne

Revision ID: 8d520174f374
Revises: 3a4aacd2f392
Create Date: 2025-04-04 19:05:08.929632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d520174f374'
down_revision: Union[str, None] = '3a4aacd2f392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
