"""[refactor] Add relation betwen User and Action tables, deleting user_creator_from Action

Revision ID: a2a754316349
Revises: cf0b7ba74984
Create Date: 2025-04-12 11:42:34.282894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2a754316349'
down_revision: Union[str, None] = 'cf0b7ba74984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('id_creator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'action', 'user', ['id_creator'], ['id_user'])
    op.drop_column('action', 'rut_creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('rut_creator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_column('action', 'id_creator')
    # ### end Alembic commands ###
