"""Create deadline and action relation

Revision ID: ae89d0e747b4
Revises: 0c0335b26536
Create Date: 2025-03-30 19:55:21.769462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae89d0e747b4'
down_revision: Union[str, None] = '0c0335b26536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deadline', ['id_deadline'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deadline', type_='unique')
    # ### end Alembic commands ###
