"""Add report table relation with action

Revision ID: c2079865df2d
Revises: d2be8f8ec118
Create Date: 2025-04-02 20:25:39.567339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2079865df2d'
down_revision: Union[str, None] = 'd2be8f8ec118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'report', ['id_report'])
    op.create_foreign_key(None, 'report', 'action', ['id_action'], ['id_action'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='unique')
    # ### end Alembic commands ###
