"""Create RefreshToken model and is_admin field in User

Revision ID: cf0b7ba74984
Revises: ffbb0a8fbcd0
Create Date: 2025-04-06 20:23:08.948219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf0b7ba74984'
down_revision: Union[str, None] = 'ffbb0a8fbcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['id_token'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
