"""Fix relation in between insitution an ppda

Revision ID: cf7fdf2423da
Revises: 152c74c63cd9
Create Date: 2025-04-04 19:09:07.486307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf7fdf2423da'
down_revision: Union[str, None] = '152c74c63cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
