"""Renew relations to Action

Revision ID: d05a5e185740
Revises: 2e27c09702e7
Create Date: 2025-04-02 20:08:51.797465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd05a5e185740'
down_revision: Union[str, None] = '2e27c09702e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline', sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'deadline', 'action', ['id_action'], ['id_action'])
    op.add_column('kpi', sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'kpi', 'action', ['id_action'], ['id_action'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kpi', type_='foreignkey')
    op.drop_column('kpi', 'id_action')
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.drop_column('deadline', 'id_action')
    # ### end Alembic commands ###
