"""Add report table

Revision ID: d2be8f8ec118
Revises: d05a5e185740
Create Date: 2025-04-02 20:24:13.924619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2be8f8ec118'
down_revision: Union[str, None] = 'd05a5e185740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_report', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_report'),
    sa.UniqueConstraint('id_report')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
