"""empty message

Revision ID: d582e83af57b
Revises: a1e4bf08ab2e
Create Date: 2025-03-30 15:03:57.122851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd582e83af57b'
down_revision: Union[str, None] = 'a1e4bf08ab2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('action_id_institution_fkey', 'action', type_='foreignkey')
    op.drop_column('action', 'id_institution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('id_institution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('action_id_institution_fkey', 'action', 'institution', ['id_institution'], ['id_institution'])
    # ### end Alembic commands ###
