"""Add history table

Revision ID: dcc07e060c7a
Revises: c2079865df2d
Create Date: 2025-04-02 20:43:09.610113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcc07e060c7a'
down_revision: Union[str, None] = 'c2079865df2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_variable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('id_history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_report'], ['report.id_report'], ),
    sa.ForeignKeyConstraint(['id_variable'], ['variable.id_variable'], ),
    sa.PrimaryKeyConstraint('id_history'),
    sa.UniqueConstraint('id_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
