"""Added Variable table

Revision ID: e8949b14e387
Revises: 75badad00f2b
Create Date: 2025-04-02 17:22:16.204024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8949b14e387'
down_revision: Union[str, None] = '75badad00f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable',
    sa.Column('id_kpi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_kpi'], ['kpi.id_kpi'], ),
    sa.PrimaryKeyConstraint('id_variable'),
    sa.UniqueConstraint('id_variable')
    )
    op.create_unique_constraint(None, 'kpi', ['id_kpi'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kpi', type_='unique')
    op.drop_table('variable')
    # ### end Alembic commands ###
