"""Remove relation from action

Revision ID: e965b9a88617
Revises: e8949b14e387
Create Date: 2025-04-02 20:05:32.204756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e965b9a88617'
down_revision: Union[str, None] = 'e8949b14e387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deadline_id_action_fkey', 'deadline', type_='foreignkey')
    op.drop_column('deadline', 'id_action')
    op.drop_constraint('kpi_id_action_fkey', 'kpi', type_='foreignkey')
    op.drop_column('kpi', 'id_action')
    op.create_unique_constraint(None, 'variable', ['id_variable'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable', type_='unique')
    op.add_column('kpi', sa.Column('id_action', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('kpi_id_action_fkey', 'kpi', 'action', ['id_action'], ['id_action'])
    op.add_column('deadline', sa.Column('id_action', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deadline_id_action_fkey', 'deadline', 'action', ['id_action'], ['id_action'])
    # ### end Alembic commands ###
