# version: '3.8'
# services:
#   service1:
#     build: .
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     # command: uvicorn app.main:app --reload --port 8080

version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    # volumes:
    #   - ./app:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

